spring:
  application:
    name: api-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/microservices
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              lower-case-service-id: true
              enabled: false
          routes:
            - id: public-users
              uri: lb://user-service
              predicates:
                - Path=/api/v1/users/**
              filters:
                - RewritePath=/api/v1/users/(?<path>.*), /api/users/$\{path}

#            - id: public-users-payments
#              uri: lb://user-service
#              predicates:
#                - Path=/api/v1/users/payments/**
#              filters:
#                - RewritePath=/api/v1/users/payments/(?<path>.*), /api/user-payments/${path}

            - id: public-orders
              uri: lb://order-service
              predicates:
                - Path=/api/v1/orders/**
              filters:
                - RewritePath=/api/v1/orders/(?<path>.*), /api/orders/$\{path}
#                - TokenRelay

server:
  port: 8085

eureka:
  client:
    service-url:
      defaultZone: http://discovery:8761/eureka/