spring:
  application:
    name: user-service

server:
  port: 0 # ${random.int(8185,8190)} #${PORT:0}

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
#    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
