spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://order-db:5432/orderdb # можно тут не писать, если есть в docker-compose
    username: orderuser # можно тут не писать, если есть в docker-compose
    password: orderpass456 # можно тут не писать, если есть в docker-compose
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update          # или validate / none в продакшене
    show-sql: true              # опционально, для отладки
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/microservices
  mvc:
    csrf:
      enabled: false
  kafka:
    bootstrap-servers: kafka-broker:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      enable-auto-commit: false
      group-id: order-service
      auto-offset-reset: earliest
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "*"
        spring.json.add.type.headers: false
        spring.json.use.type.headers: false
        spring.json.value.default.type: dev.folomkin.orderservice.kafka.consumer.PaymentCompletedEvent


server:
  port: ${SERVER_PORT:0}

eureka:
  instance:
    instance-id: $${spring.application.name}:${random.uuid}
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://discovery:8761/eureka #http://discovery:8761/eureka
logging:
  level:
    org.springframework.security: TRACE   # или DEBUG
    org.springframework.web: DEBUG
