spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://order-db:5432/orderdb # можно тут не писать, если есть в docker-compose
    username: orderuser # можно тут не писать, если есть в docker-compose
    password: orderpass456 # можно тут не писать, если есть в docker-compose
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update          # или validate / none в продакшене
    show-sql: true              # опционально, для отладки
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/microservices
  mvc:
    csrf:
      enabled: false

server:
  port: ${SERVER_PORT:0}

eureka:
  instance:
    instance-id: $${spring.application.name}:${random.uuid}
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://discovery:8761/eureka #http://discovery:8761/eureka
logging:
  level:
    org.springframework.security: TRACE   # или DEBUG
    org.springframework.web: DEBUG
kafka:
  bootstrap-servers: kafka:9092
  producer:
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  properties:
    spring.json.add.type.headers: false